program: train.py  # Your training script

method: grid  # Hyperparameter optimization method

metric:
  goal: minimize  # Modify as per your use case
  name: Test Contrastive Loss  # Replace with your metric
  
name: Temperature Learnable, 257 Tokens # Sequence Contrasting Width 1024, Batch 256, grad clipping, no video perceiver, weighted avg all token of perceiver, 1024 sweeper on lr and dropout, extra class token, SCALING TEMP temperature rescaling loss remapper

parameters:
  batch_size:
    #values: [256,512,1024]
    value: 256
  virtual_batch_size:
    #values: [32,64,128,256,1024]
    value: -1
  num_batches:
    value: 28
    #values: [4, 8, 12, 16, 20, 24, 28]
  contrast_on_sequence:
    value: true
  loss_remapping:
    value: true
  num_encoders:
    value: 1
  token_num:
    #values: [5, 53]
    value: 0 #[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]
  learning_rate:
    value: 0.0003
    #min: 0.0001
    #max: 0.001
  dropout:
    value: 0.3
    #min: 0.0
    #max: 0.5
  num_epochs:
    value: 3000
  projected_embeds:
    value: false
  use_supervised_loss:
    values: [true, false]
    #value: false
  use_contrastive_loss:
    value: 'infonce'
  checkpoint_dir:
    value: '../Checkpoints'
  num_workers:
    value: 4
  use_perceiver:
    #values: [false, true]
    value: false
  use_perceiver_on_video_only:
    #values: [false, true]
    value: false
  supervised_on_perceiver:
    #values: [false, true]
    value: false
  metrics_on_perceiver:
    #values: [true, false]
    value: false
  num_training_steps:
    value: 13000
  early_stopping_patience:
    value: 30
  early_stopping_delta:
    value: 0.01
  use_wandb:
    value: true
  patch_size:
    #values: [16, 64, 128]
    value: 16
  padding:
    value: 0
  width:
    #values: [256,512,1024]
    value: 256
  num_layers:
    value: 8
  num_heads:
    value: 8